# -*- coding: utf-8 -*-
"""NLP_mini_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vKHfZ7OmAHoAa_RvwqjfCadvahdLmH2n

# NLP-Based Movie Genre Classification Using TF-IDF and Machine Learning

## Project Overview

This project aims to automatically classify movies into different genres based on their descriptions using Natural Language Processing (NLP) and Machine Learning.

The movie descriptions are first preprocessed and converted into numerical features using TF-IDF. Two machine learning algorithms, Logistic Regression and Multinomial Naive Bayes, are then trained and evaluated for movie genre classification.

## Step 1: Import Required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

from google.colab import files

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')

print("Libraries imported successfully.")

"""## Step 2: Upload Dataset

"""

uploaded = files.upload()

"""## 3. Load Dataset"""

file_name = list(uploaded.keys())[0]

df = pd.read_csv(file_name)

print("Dataset loaded successfully.")

"""## 4. Dataset Overview"""

print("Dataset Shape:", df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

df.head()

df.info()

"""## 5. Check Missing Values"""

missing_values = df.isnull().sum()

print("Missing values in each column:")
print(missing_values)

"""## 6. Check Duplicate Records"""

duplicate_count = df.duplicated().sum()

print("Number of duplicate records:", duplicate_count)

"""## 7. Explore Movie Genres"""

genre_counts = df['GENRE'].value_counts()

print("Number of unique genres:", df['GENRE'].nunique())

print("\nGenre distribution:")
print(genre_counts)

plt.figure(figsize=(12, 6))

genre_counts.plot(kind='bar')

plt.title("Distribution of Movie Genres")
plt.xlabel("Genre")
plt.ylabel("Number of Movies")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""## 8. Select Movie Genres

To keep the classification task manageable, eight well-represented movie genres are selected for the project.
"""

selected_genres = [
    'drama',
    'documentary',
    'comedy',
    'short',
    'horror',
    'thriller',
    'action',
    'western'
]

df = df[df['GENRE'].isin(selected_genres)].copy()

print("Selected genres:")
print(selected_genres)

print("\nDataset shape after genre selection:", df.shape)

selected_genre_counts = df['GENRE'].value_counts()

print(selected_genre_counts)

plt.figure(figsize=(10, 5))

selected_genre_counts.plot(kind='bar')

plt.title("Distribution of Selected Movie Genres")
plt.xlabel("Genre")
plt.ylabel("Number of Movies")
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

"""## 9. Data Cleaning"""

df = df.dropna(subset=['DESCRIPTION', 'GENRE'])

df = df.drop_duplicates(subset=['DESCRIPTION'])

print("Dataset shape after cleaning:", df.shape)

df[['TITLE', 'GENRE', 'DESCRIPTION']].head(10)

# Apply preprocessing to all SMS messages

data["clean_message"] = data["message"].apply(preprocess_text)

data.head()

"""## 10. Text Preprocessing"""

stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    text = text.lower()

    text = re.sub(r'[^a-zA-Z\s]', '', text)

    words = text.split()

    words = [
        word for word in words
        if word not in stop_words
    ]

    text = ' '.join(words)

    return text

example = df['DESCRIPTION'].iloc[0]

print("Original Description:")
print(example)

print("\nAfter Preprocessing:")
print(preprocess_text(example))

df['CLEANED_DESCRIPTION'] = df['DESCRIPTION'].apply(preprocess_text)

df[['DESCRIPTION', 'CLEANED_DESCRIPTION']].head()

df = df[df['CLEANED_DESCRIPTION'].str.strip() != '']

print("Final dataset shape:", df.shape)

"""## 11. Prepare Data for Classification"""

X = df['CLEANED_DESCRIPTION']
y = df['GENRE']

print("Number of input samples:", len(X))
print("Number of target samples:", len(y))
print("Number of classes:", y.nunique())

"""## 12. Train-Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

"""## 13. TF-IDF Feature Extraction"""

tfidf_vectorizer = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1, 2),
    min_df=2
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

"""## 14. Logistic Regression"""

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

logistic_predictions = logistic_model.predict(X_test_tfidf)

print("Logistic Regression training completed.")

logistic_accuracy = accuracy_score(
    y_test,
    logistic_predictions
)

print(f"Logistic Regression Accuracy: {logistic_accuracy:.4f}")
print(f"Logistic Regression Accuracy: {logistic_accuracy * 100:.2f}%")

print("Logistic Regression Classification Report:\n")

print(
    classification_report(
        y_test,
        logistic_predictions,
        zero_division=0
    )
)

"""## 15. Multinomial Naive Bayes"""

naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(
    X_train_tfidf,
    y_train
)

naive_bayes_predictions = naive_bayes_model.predict(
    X_test_tfidf
)

print("Multinomial Naive Bayes training completed.")

naive_bayes_accuracy = accuracy_score(
    y_test,
    naive_bayes_predictions
)

print(f"Naive Bayes Accuracy: {naive_bayes_accuracy:.4f}")
print(f"Naive Bayes Accuracy: {naive_bayes_accuracy * 100:.2f}%")

print("Naive Bayes Classification Report:\n")

print(
    classification_report(
        y_test,
        naive_bayes_predictions,
        zero_division=0
    )
)

"""## 16. Model Comparison"""

model_comparison = pd.DataFrame({
    'Model': [
        'Logistic Regression',
        'Multinomial Naive Bayes'
    ],
    'Accuracy': [
        logistic_accuracy,
        naive_bayes_accuracy
    ]
})

model_comparison['Accuracy (%)'] = (
    model_comparison['Accuracy'] * 100
)

model_comparison

plt.figure(figsize=(8, 5))

plt.bar(
    model_comparison['Model'],
    model_comparison['Accuracy (%)']
)

plt.title("Model Accuracy Comparison")
plt.xlabel("Model")
plt.ylabel("Accuracy (%)")

plt.ylim(0, 100)

plt.tight_layout()
plt.show()

"""## 17. Select the Best Model"""

if logistic_accuracy >= naive_bayes_accuracy:
    best_model = logistic_model
    best_model_name = "Logistic Regression"
    best_predictions = logistic_predictions
    best_accuracy = logistic_accuracy
else:
    best_model = naive_bayes_model
    best_model_name = "Multinomial Naive Bayes"
    best_predictions = naive_bayes_predictions
    best_accuracy = naive_bayes_accuracy

print("Best Model:", best_model_name)
print(f"Best Model Accuracy: {best_accuracy * 100:.2f}%")

"""## 18. Confusion Matrix"""

cm = confusion_matrix(
    y_test,
    best_predictions,
    labels=selected_genres
)

plt.figure(figsize=(10, 8))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=selected_genres,
    yticklabels=selected_genres
)

plt.title(f"Confusion Matrix - {best_model_name}")
plt.xlabel("Predicted Genre")
plt.ylabel("Actual Genre")

plt.xticks(rotation=45)
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

"""## 19. Final Model Evaluation"""

print(f"Final Model: {best_model_name}")
print(f"Accuracy: {best_accuracy * 100:.2f}%\n")

print(
    classification_report(
        y_test,
        best_predictions,
        zero_division=0
    )
)

"""## 21. Predict Genre for a New Movie"""

def predict_movie_genre(description):
    cleaned_description = preprocess_text(description)

    description_tfidf = tfidf_vectorizer.transform(
        [cleaned_description]
    )

    prediction = best_model.predict(
        description_tfidf
    )

    return prediction[0]

new_movie = """
A detective investigates a series of mysterious murders
that have occurred in a small town.
"""

predicted_genre = predict_movie_genre(new_movie)

print("Movie Description:")
print(new_movie)

print("\nPredicted Genre:")
print(predicted_genre)

"""## 22. Interactive Movie Genre Prediction"""

movie_description = input(
    "Enter a movie description: "
)

predicted_genre = predict_movie_genre(
    movie_description
)

print("\nPredicted Movie Genre:", predicted_genre)

test_movies = [

    "A detective follows clues to solve a mysterious murder involving several suspects.",

    "Two people from different backgrounds meet and gradually fall in love.",

    "A family goes on an exciting journey across the country and faces many unexpected adventures."
]

for description in test_movies:
    prediction = predict_movie_genre(description)

    print("Description:")
    print(description)
    print("Predicted Genre:", prediction)
    print("-" * 80)

"""## 23. Project Summary"""

print("==============================================")
print("       MOVIE GENRE CLASSIFICATION")
print("==============================================")

print(f"Original Dataset Size: 108414 movies")
print(f"Final Dataset Size: {len(df)} movies")
print(f"Number of Genres: {y.nunique()}")
print(f"Training Samples: {len(X_train)}")
print(f"Testing Samples: {len(X_test)}")
print(f"TF-IDF Features: {X_train_tfidf.shape[1]}")

print("\nModels Used:")
print("1. Logistic Regression")
print("2. Multinomial Naive Bayes")

print(f"\nBest Model: {best_model_name}")
print(f"Best Accuracy: {best_accuracy * 100:.2f}%")

print("==============================================")

"""## 24. Conclusion

The project developed an NLP-based movie genre classification system using movie descriptions.

The movie descriptions were cleaned and preprocessed before being converted into numerical representations using TF-IDF. Two machine learning algorithms, Logistic Regression and Multinomial Naive Bayes, were trained to classify movies into eight selected genres.

The models were evaluated using accuracy, precision, recall, F1-score, and a confusion matrix. The better-performing model was selected as the final classifier.

The completed system can also accept a new movie description and predict its most likely genre, demonstrating a practical application of NLP and machine learning.
"""